### ISSUE TITLE
Fragment parsing

### ISSUE THREAD

**Issue by xmo-odoo** [kovidgoyal/html5-parser#15]
The documentation only mentions a single method, but doesn't seem to say anything about fragments.

Is there a way to parse fragments (as non-document) with html5parser?

**Comment by kovidgoyal** [comment]
Fragments parse fine already as far as I know.

**Comment by kovidgoyal** [comment]
When would you possibly want to parse something as a fragment or a document. Either you want fragments or you want documents, the two are incompatible. If you want your parsing to result in fragments, simply add a "<div>" to the start of the string, parse it and return the first div from the parse tree. If you want your parsing to result it documents, you dont need to do anything.
