### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by stoecker** [kovidgoyal/html5-parser#4]
On openSUSE 42.1 it fails due to an ISO-C90 violation (probably caused by a strict compiler option):

https://build.opensuse.org/public/build/home:dstoecker/openSUSE_Leap_42.1/x86_64/python-html5-parser/_log

src/python-wrapper.c:78:5: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
src/python-wrapper.c:82:5: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
src/python-wrapper.c:112:5: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
src/python-wrapper.c:128:5: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]

Could you please fix these warnings/errors?

**Comment by kovidgoyal** [comment]
html5-parser requires a C99 compiler. As far as I know, mixed declarations and code are perfectly valid in C99. I'm afraid I am not interested in adding support for compilers that are old enough to not support C99.

**Comment by wumpus** [comment]
The compiler is gcc 4.8, which supports C99. stoecker should look into why -Werror=declaration-after-statement is in the gcc command line.

**Comment by kovidgoyal** [comment]
The compiler flags come from the python build system. html5-parser's setup.py only adds the following flags:

-O3 -std=c99 -fvisibility=hidden
