### ISSUE TITLE
Any options to use on AWS Lambda?

### ISSUE THREAD

**Issue by franchb** [kovidgoyal/html5-parser#9]
I want to make an HTML scraper periodically running as AWS Lambda function.

Is there any option to use `html5-parser`? I don't know how to manage `pip install --no-binary lxml html5-parser` and C99 on AWS Lambda...

**Comment by kovidgoyal** [comment]
No idea, I dont use AWS Lambda. Presumably you have to get whoever maintains the software on AWS Lambda to install html5-parser to make it available for use.

**Comment by 21stio** [comment]
sure, you have to ship your dependencies with your lambda functions

maybe have a look into 

https://serverless.com/blog/serverless-python-packaging/
